#!/bin/sh

if [ $# -eq 0 ] ; then
    echo "usage: ./test executable \"testcases\" targetdir refdir"
    echo "usual testcases is \"\", usual refdir is ref"
    echo "example: ./test ../../../bin/ugshell \"\" my_test ref"
    exit 1
else
    \mkdir -p $3
    \mkdir -p vtk # needed for VTKout. TODO: reference VTK?
    \rm -f $3/$2.diffs
    for ii in $2*.sh; do
	echo $ii
	echo $ii >>$3/$2.diffs
	UGSHELL=$1 ./$ii | tail -n +12 | sed '/^Loading Plugin Lua Content/d' >$3/$ii.out
	diff -u $4/$ii.out $3/$ii.out >>$3/$2.diffs || echo "**** $ii fails ****"
    done
    # for ii in $2*.lua; do
    #     echo $ii
    #     echo $ii >>$3/$2.diffs
    #     $UGSHELL -ex $ii >$3/$ii.out
    #     diff -u $4/$ii.out $3/$ii.out >>$3/$2.diffs || echo "**** $ii fails ****"
    # done
    echo done with $1 $2 >>$3/$2.diffs
    echo done with $1 $2
    exit 0
fi

# vim:ts=8:sw=8:
